server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Compression GZIP
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/webp;

    # Static Assets & WebP caching
    location ~* \.(?:ico|css|js|gif|jpe?g|png|webp|svg|woff2?|eot|ttf)$ {
        expires 6m;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # API REST Proxy
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Uploads Proxy
    location /uploads/ {
        proxy_pass http://backend:5000/uploads/;
    }

    # React Single Page App fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
